### ISSUE TITLE
Could you add the pretrained target classifier and full training data?

### ISSUE THREAD

**Issue by yuxy411** [cookielee77/CLARE#2]
Hi, thanks for this wonderful work.
I can't get the same results with my pretrained model, could you add your pretrained target classifier or full training data? That will be very helpful.

**Comment by cookielee77** [comment]
Sorry for running late on this as I graduated from school. I re-trained the models which should have comparable results. The download link was updated on the page. Please note that the target classifers from the link or used in the paper were trained much robust compared with the victim models from Textfooler.
