### ISSUE TITLE
Approximate time required per attack? 

### ISSUE THREAD

**Issue by bangawayoo** [cookielee77/CLARE#3]
Hi, 
Thank you for the awesome work!

Do you have an estimate of how much time is required per attack on one of the dataset?  
I was using the implemented version of CLARE in TextAttack and found out that it took a substantial amount of time to generate attacks. Around several hours on 1080Ti to generate < 100 attack samples. 
I am wondering if this is an expected behavior (given that ROBERTa is forwarded multiple times)? or an implementation issue on their side?

Thanks!

**Comment by cookielee77** [comment]
Hi, 

Thanks for the contact. I think I have some specific optimizations for my implementation (e.g., try to utilize all memory in one GPU for 1080Ti). The speed for the AG news 1000 sample should be generated within 3 hrs on my end. I don't think they have integrated the corresponding parts in their implementation. 

Thanks!
